electron/windows-installer

README.md
index.coffee

An authentication token option `-t` is supported by SyncReleases.exe
It is necessary for connecting to private repos.
Thanks for making this repo!  I've been using a custom port of `grunt-electron-installer` and this is the only difference from the code that I have in production.

Add remoteToken option

---

README.md

The Docs say that electron-winstaller uses callbacks, but it actually returns a Promise

Docs: electron-winstaller uses promises

---

src/index.js

I had a empty description in my package.json and a description in the options but it didn't work.
It says this in the readme `Defaults to the description field from your app's package.json file when unspecified.` so I guess appMetaData should not override options...

options should override app meta data, not the other way round

---

.travis.yml
README.md
appveyor.yml

Attempting to fix `EPERM` errors like: https://ci.appveyor.com/project/kevinsawicki/windows-installer/build/1.0.85 by using npm 3 on AppVeyor.
Seems related to https://github.com/npm/npm/issues/9696 and http://help.appveyor.com/discussions/problems/3147-error-eperm-operation-not-permitted-rename-on-npm-install
Also adds `node_modules/` caching to both builds and only building master branch and pull requests by default to prevent double statuses for Travis and AppVeyor.

Use latest npm on AppVeyor

---

template.nuspec

Use forward slashes instead of backslashes in .nuspec. I suppose that backslashes in path spec have to be quoted with another backslash, but historically one can use forward slashes in paths while opening files programmatically. The safe way is to use forward slashes in .nuspec and nuget.exe understands them perfectly.

Fix copying resources and locales to installer

---

src/index.js

electron-builder has own naming policy — don't rename twice.

add option fixUpPath to disable artifacts renaming

---

.babelrc
package.json
spec/support.js
src/babel-maybefill.js
src/index.js

I think, it is ok to support only NodeJS 4+.

use babel es2015-node4 — we can require nodejs 4

---

.editorconfig
.gitignore
package.json
spec/installer-spec.js
src/fs-utils.js
src/index.js
src/spawn-promise.js

fs-jetpack uses Q instead of bluebird, Q doesn't support long stack traces.
Also jetpack had wrong behavior with absolute paths.
Cleaned up es6.
Added .editorconfig.
@develar could you please review this patch?
/cc @paulcbetts @kevinsawicki

Replaced fs-jetpack with promised functions from fs and fs-extra.

---

README.md
src/index.js

This lets the user select a name for the generated `Setup.exe` file.

Add `setupExe` option

---

README.md

To avoid https://github.com/electron-userland/electron-builder/issues/279#issuecomment-205832181

Add info about electron-squirrel-startup

---

src/index.js

This sets `Update.exe` to have the same icon as your generated Setup executable.

Set the Update.exe icon appropriately

---

src/index.js

Invoke `rcedit.exe` through `wine` when available so you can set the `Update.exe` icon when building your installer from Mac/Linux.
Follow on to #59
Previously it would fail with the following error on Mac/Linux:
```
Error: spawn EACCES
at exports._errnoException (util.js:870:11)
at ChildProcess.spawn (internal/child_process.js:298:11)
at exports.spawn (child_process.js:362:9)
```

Set Update.exe icon using wine when available

---

src/index.js

Previously if the `setupExe` option was specified but not `productName` then the `Setup.exe` would not get renamed since their was a `productName` check earlier to enter the rename block that would not pass.
This pull request changes that so that `Setup.exe` will be renamed if `productName` **or** `setupExe` is specified.
This also adds logging when the `.msi` path is renamed for consistency with the logging done for the `Setup.exe` rename.
Follow on to #60 
/cc @feross

Fixup setup path when setupExe but no productName

---

src/index.js

I'm seeing a weird issue where calling `rcedit.exe --set-icon` on the `Update.exe` through wine is corrupting it somehow and making it non-launchable.
So this pull request adds an option called `skipUpdateIcon` that will start out as undocumented so that people can disable changing the `Update.exe` icon but still have the `Setup.exe` icon set.
I was am using Wine 1.8.1 on Mac OS X 10.10.5 and seeing it fail to launch on Windows 10

Add option to skip setting update icon

---

src/index.js

We use wine/mono only on non-windows platform (i.e. not not on invalid platform that requires such workaround).
less code – less bugs. btw, electron-builder/electron-packager don't use such hack and in any case we use wine/mono only on normal platforms, not on windows.

remove locateExecutableInPath

---

package.json

Cf. #83 for report.
(tilde would work just as well as caret, might make sense since asar is in 0.x — alternatively, asar could be updated to [respect semver](https://docs.npmjs.com/getting-started/semantic-versioning#semver-for-publishers))

Upgrade asar to drop dependency on deprecated graceful-fs@3

---

template.nuspectemplate

Following change adds the Chromium Licenses HTML file to the Installer as it's not shipped with it currently.
Also, I am using a 3rd Party notices file like [VS Code](https://github.com/Microsoft/vscode/blob/master/ThirdPartyNotices.txt) and It's right next to the LICENSE file. So I added text files for packaging also.
Fixes #131

add: *.txt & LICENSES.chromium.html files to nuspec

---

README.md

I've been looking for a way to override windows `appId` (to set final directory for my app in `%user%/AppData/Local/<name>`). And found that there is a `name` option that do this, but it was missed in README.

Missed name setting in README

---

package.json

Fixes issue that caused `Unable to load file` when add setupIcon configuration.
see #233

Update fs-extra to 2.1.2

---

README.md

The option `skipUpdateIcon` was not documented, but seems necessary when using `setupIcon` to avoid error messages. I could only find it in a comment buried in a closed issue (https://github.com/electron/windows-installer/issues/81#issuecomment-243665425).

Documented "skipUpdateIcon" option.

---

src/index.js

Changed the logic in parsing the signWithParams to allow for using them alongside the certificate options, rather than instead of them.
This stems from times I was debugging the signing procedure, or wanted to tweak it, but wished to do so without manually building the arguments for the certificate file and password as well.
To make this change non-breaking, I added a conditional testing that the user-provided signWithParams contain neither /f nor /p, and only in the case that neither of those exists and both certificateFile and certificatePassword are provided, both are used. Otherwise the behavior is just as it currently is.
I would love to hear thoughts about this change, and if there reasons I might be missing why it's a bad idea. I'm also unsure about how to test it - is there a test …

Allowed signWithParams with certificateFile/Password

---

.circleci/config.yml
src/index.ts

On 64-bit macOS/Linux, use `wine64` instead of `wine`. This should fix some (but not all) problems with running this module on macOS Catalina (10.15).
This also fixes the macOS CI. It is currently pinned to macOS 10.14 due to the Catalina issues.

fix: use 64-bit wine when necessary

---

src/index.ts
src/options.ts

The icon in the Electron repository was moved a while ago but it wasn't updated here.

fix: update default iconUrl value since it moved

---

package.json
yarn.lock

`semantic-release` is [currently failing](https://app.circleci.com/pipelines/github/electron/windows-installer/99/workflows/e7b893b5-ba43-4d09-99ce-2233890c7a3f/jobs/168):
```
[3:24:22 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Unexpected status when starting proof process on CircleCI: 503
at Object.exports.getProofThroughCircleCI (/home/circleci/project/node_modules/@continuous-auth/client/lib/module/circleci.js:12:15)
at process._tickCallback (internal/process/next_tick.js:68:7) pluginName: '@continuous-auth/semantic-release-npm' }
{ Error: Unexpected status when starting proof process on CircleCI: 503
at Object.exports.getProofThroughCircleCI (/home/circleci/project/node_modules/@continuous-auth/client/lib/module/circleci.js:12:15)
at …
```

chore: upgrade to version 2 of the CFA client

---

.circleci/config.yml

Should address recent CI failures on macOS by using `brew install --cask` instead of the deprecated `brew cask` command.

ci: Use brew install --cask to fix macOS CI failures

---

src/index.ts
src/options.ts

This change aims to increase the type clarity of winstaller's `options`.  This will increase readability in our docs when documenting types for Squirrel.Windows.

feat!: rename Options to SquirrelConfigOptions

---

spec/convert-version-spec.ts
src/index.ts

I assume the purpose of `convertVersion` is to convert the version string to semver 1.0 standard which Squirrel can support. So it might as well drop the build metadata part specified in [semver 2.0](https://semver.org/spec/v2.0.0.html#spec-item-10), denoted by a `+` sign. Since by specification, the build metadata has no effect on precedence, I think it makes sense to simply discard it instead of incorporating it.

fix: Drop build metadata part in convertVersion

---

.circleci/config.yml
package.json
yarn.lock

Fixes the CI build for Windows and Linux. macOS is still having an error across the board which needs to be looked into.
Uses `electronjs/node` orb to pick up caching of Node.js installs, expand the test matrix, and simplify this CircleCI config.

ci: use electronjs/node orb

---

src/index.ts

The old code wrongly checked if Mono and Wine were installed. It looked like this:
https://github.com/electron/windows-installer/blob/073930d4845432adb2f16891c81066249cf99c71/src/index.ts#L26-L40
The part `(!wineExe || !monoExe)` didn't work right because wineExe and monoExe were just text, not real checks.
Now, the code really checks if Wine and Mono are there. This fix makes sure the setup works right and checks everything needed.

fix: Corrected the verification of Mono and Wine installation status

---

package.json

The default timeout is 10s and we keep tripping it on Windows CI.

test: bump ava test timeout

---

.circleci/config.yml
.gitignore
README.md
package.json
spec/helpers/helpers.ts
spec/helpers/windowsSignHook.js
spec/installer-spec.ts
spec/sign-spec.ts
src/index.ts
src/options.ts
src/sign.ts
yarn.lock

This PR enables `@electron/windows-sign` to "hijack" codesigning within Squirrel. It does so by using `@electron/windows-sign`'s ability to create a custom `signtool.exe` that's _actually_ a "single executable application" built with Node.js, calling `@electron/windows-sign` underneath. 
This, in turn, allows developers to customize their codesigning pipelines - with custom tools, scripts, and even per-file configurations. Now that Windows will only accept EV Codesigning certificates, many developers are faced with codesigning scenarios that are more complex - involving custom tooling, cloud-based solutions, and other shenanigans. 
For details on how this all works underneath the hood, check out https://github.com/electron/windows-sign/commit/8b23eaa900b4ca0905699b4fa17ca22246624fdf
- …

feat: Allow @electron/windows-sign to take over Squirrel codesigning

---

.circleci/config.yml
.gitignore
README.md
package.json
src/index.ts
src/options.ts
typedoc.json
yarn.lock

Mostly refining our existing option descriptions with links and better usage of TSDoc-style `@tags` for improved IntelliSense.

docs: improve API descriptions
